### ISSUE TITLE
cat1.plot() is not adjusted to screen size and overflows

### ISSUE THREAD

**Issue by Bisaloo** [groundhogR/groundhogR#12]
![image](https://user-images.githubusercontent.com/10783929/78491778-fd586200-7748-11ea-83bd-8541863e4954.png)

**Comment by urisohn** [comment]
There are a few ways to address this.
I had thought people would just naturally resize the plot size if they were interested.
Not a terrible outcome.

One could have the message check the size of teh plot and if it is not big enough, to instead of showing the actual messasge, to read "please make this area bigger if you would like to see the information being printed here".

but I am inclined to leave as is unless you feel strongly

**Comment by Bisaloo** [comment]
I don't have a good solution right now so let's leave it as is but we can keep this issue open in case there is an easy fix. It would be much nicer to be able to read everything without having to resize.

**Comment by urisohn** [comment]
There is a solutin. One can have a window popup for the plot and that is easier to resize, but i rather not rely on popups. I think this is fine. People are used to adjusting plot size by hand when they plot. ANd they are there bored in front of their screens anyway. Waiting for the many minutes that source will take, or the mssage is not relevant anyway.
