### ISSUE TITLE
add quiet.groundhog option

### ISSUE THREAD

**Issue by urisohn** [groundhogR/groundhogR#42]
was thinking that adding that option to the groundhog.library(,quiet.groundhog=FALSE) and that if true it led message1 and message2 to go quiet could make sense.

so adding a conditional to message1 and message2 that only if quiet.groundhog==TRUE they print

**Comment by Bisaloo** [comment]
Most groundhogR functions already have a lot of arguments so I don't know if it's a great idea to add another one.

Here is a counter-proposal:

- rename `quiet.install` to `quiet` and disable all messages (including `message1()` and `message2()`).
- possibly, change `quiet` to a argument that specifies the level of verbosity instead of a `TRUE`/`FALSE` argument. `0  would print all messages, `1` would leave only groundhogR messages and `2` would remove all messages. (If we go this route, it seems more intuitive to actually do this opposite with an argument named `verbose`).

 It's common practice in other pieces of software to have different levels of verbosity.

**Comment by urisohn** [comment]
OK. I am on board with a verbosity parameter with multiple levels as a solution.

**Comment by Bisaloo** [comment]
To make sure we're on the same page, this change applies to `install.snowball()` and `install.source()` as well, right?

**Comment by urisohn** [comment]
Yes.
But, to clarify further.
I think in practice the two key things to want to slien are
source output (which is way too voluminous and a good default to prevent)
message1 and message2, i think tech oriented users may want to turn it off.
But i don't think very often people want to turn off all other output, say that from the download() or other direct R output. 
So there is 
0, show all
1. don't show source output
2. don't show groundhog output (message1 and message2)
3. don't show anything

Does that make sense?

**Comment by Bisaloo** [comment]
Ok, I'll think about the best way to do this.

In the meantime, I added a nice feature that leverages a new feature from R 4.0.0 (it has no effect whatsoever on earlier versions):

```
suppressMessages(groundhog.library("lightr", "2020-01-01"), classes = "groundhog-msg")
```

will run `groundhog.library("lightr", "2020-01-01")` without printing any of `message1()` or `message2()`

**Comment by urisohn** [comment]
nice feature for 4.0

i actually tend to think it will be simpler to keep the package as is, and add a parameter to the function that is quiet.groundhog=T/F and that parameter.

**Comment by Bisaloo** [comment]
The more I think about it, the more it strikes me as something that should be controlled via options. Because `message1()` and `message2()` are in almost every function, it would force us to add a `quiet.groundhog` argument everywhere.

An alternative is what usethis does: https://github.com/r-lib/usethis/blob/c0acd1b5e43f03773a5934c1d937bf70b77a2557/principles.md#communicating-with-the-user

If the user wants to remove all groundhog messages, they would just need to set `options(quiet.grounhog = TRUE)`.

What do you think think of this?

**Comment by urisohn** [comment]
yeah, that sounds good. Thanks.
